linters-settings:
  misspell:
    locale: US

issues:
  exclude-dirs:
    - .devcontainer
    - .github
    - postgres
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - goerr113
    - path: cmd/
      text: commit is a global variable
      linters:
        - gochecknoglobals
    - path: cmd/
      text: buildDate is a global variable
      linters:
        - gochecknoglobals
