version: "3.8"
services:
  hano_scraper:
    build: .
    image: owodunni/hano_scraper
    container_name: hano_scraper
    ports:
      - 8000:8000/tcp
    restart: always

  postgres:
    image: postgres:16-alpine
    container_name: hano_scraper_postgres
    volumes:
      - hano_scraper:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hano_scraper
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  hano_scraper:
